### ISSUE TITLE
TIPCC: sequenza 3.0.0 fail to install on TIPCC

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/Costello-PSCN-Seq#24]
# Issue

The new [sequenza 3.0.0](https://cran.r-project.org/package=sequenza) depends on [seqminer](https://cran.r-project.org/package=seqminer), which fails to install on TIPCC.  We get installation errors such as:
```sh
> install.packages("seqminer")
...
/tmp/henrik/ccjlyQXx.s: Assembler messages:
/tmp/henrik/ccjlyQXx.s:460: Error: no such instruction: `shlx %r11,%r9,%r9'
/tmp/henrik/ccjlyQXx.s:488: Error: no such instruction: `shlx %r10,%rcx,%rcx'
/tmp/henrik/ccjlyQXx.s:533: Error: no such instruction: `shrx %rcx,%r9,%r9'
/tmp/henrik/ccjlyQXx.s:620: Error: no such instruction: `shlx %rsi,%rcx,%rcx'
/tmp/henrik/ccjlyQXx.s:648: Error: no such instruction: `shlx %rax,%rsi,%rax'
/tmp/henrik/ccjlyQXx.s:673: Error: no such instruction: `shlx %r13,%rsi,%rsi'
/tmp/henrik/ccjlyQXx.s:691: Error: no such instruction: `shlx %r10,%rsi,%rsi'
/tmp/henrik/ccjlyQXx.s:753: Error: no such instruction: `shrx %rsi,%rcx,%r9'
/tmp/henrik/ccjlyQXx.s:771: Error: no such instruction: `shlx %rsi,%rcx,%rcx'
make: *** [zstd/lib/compress/huf_compress.o] Error 1
ERROR: compilation failed for package 'seqminer'
```

# Troubleshooting

This falls under TIPCC is outdated.  

# Workaround

I've attempted various suggestions adding compiler flags such as
```
PKG_CFLAGS += -mno-fma -mno-avx2 -march=bdver1
PKG_CPPFLAGS += -mno-fma -mno-avx2 -march=bdver1
```
to R-specific ~/.R/Makevars file but it made no difference.

A workaround is to install an older version of seqminer.  The following works on TIPCC with R 3.6.1;
```r
install.packages("https://cran.r-project.org/src/contrib/Archive/seqminer/seqminer_6.1.tar.gz")
```
After installing that, 
```r
install.packages("sequenza")
```
works.
